const ACTION_TYPES = {
  ACTION1: "ACTION1",
  SET_SSID: "SET_SSID",
  SET_BLUETOOTH_CONNECTION: "SET_BLUETOOTH_CONNECTION",
  SET_BLUETOOTH_DEVICE: "SET_BLUETOOTH_DEVICE",
  SET_BLUETOOTH_STATUS: "SET_BLUETOOTH_STATUS",
};

export default ACTION_TYPES; 