const ACTION_TYPES = {
  ACTION1: "ACTION1",
  SET_SSID: "SET_SSID",
  FETCH_SSIDS_START: "FETCH_SSIDS_START",
  FETCH_SSIDS_SUCCESS: "FETCH_SSIDS_SUCCESS",
  FETCH_SSIDS_FAILURE: "FETCH_SSIDS_FAILURE",
};

export default ACTION_TYPES; 